*** Starting uWSGI 2.0.19.1 (64bit) on [Sun Jun 20 15:09:22 2021] ***
compiled with version: 8.3.0 on 20 June 2021 14:59:02
os: Linux-5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020
nodename: 96cbaeb77dc8
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /app
writing pidfile to /tmp/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.10 (default, May 12 2021, 16:05:48)  [GCC 8.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x56088aad57e0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 11 seconds on interpreter 0x56088aad57e0 pid: 11 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 11)
spawned uWSGI worker 1 (pid: 25, cores: 1)
...brutally killing workers...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /app
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (0.0.0.0:9090)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from /etc/uwsgi/uwsgi.ini
*** Starting uWSGI 2.0.19.1 (64bit) on [Sun Jun 20 15:11:32 2021] ***
compiled with version: 8.3.0 on 20 June 2021 14:59:02
os: Linux-5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020
nodename: 96cbaeb77dc8
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /app
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 0.0.0.0:9090 fd 3
*** Starting uWSGI 2.0.19.1 (64bit) on [Sun Jun 20 15:20:08 2021] ***
compiled with version: 8.3.0 on 20 June 2021 15:16:08
os: Linux-5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020
nodename: b7dad714e9df
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /app
writing pidfile to /tmp/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.10 (default, May 12 2021, 16:05:48)  [GCC 8.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x564a748957e0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 4 seconds on interpreter 0x564a748957e0 pid: 10 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 10)
spawned uWSGI worker 1 (pid: 20, cores: 1)
[pid: 20|app: 0|req: 1/1] 172.22.0.1 () {44 vars in 1332 bytes} [Sun Jun 20 15:53:13 2021] GET / => generated 43 bytes in 38 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 2/2] 172.22.0.1 () {46 vars in 1363 bytes} [Sun Jun 20 15:55:37 2021] GET / => generated 43 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 3/3] 172.22.0.1 () {28 vars in 350 bytes} [Sun Jun 20 15:55:43 2021] GET /health => generated 43 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 4/4] 172.22.0.1 () {32 vars in 402 bytes} [Sun Jun 20 15:55:43 2021] POST /setup => generated 31 bytes in 3040 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 5/5] 172.22.0.1 () {28 vars in 350 bytes} [Sun Jun 20 15:55:46 2021] GET /health => generated 43 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 6/6] 172.22.0.1 () {32 vars in 402 bytes} [Sun Jun 20 15:55:46 2021] POST /setup => generated 31 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 7/7] 172.22.0.1 () {28 vars in 350 bytes} [Sun Jun 20 15:55:47 2021] GET /health => generated 43 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 8/8] 172.22.0.1 () {32 vars in 402 bytes} [Sun Jun 20 15:55:47 2021] POST /setup => generated 31 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 9/9] 172.22.0.1 () {32 vars in 403 bytes} [Sun Jun 20 15:55:54 2021] POST /train => generated 47 bytes in 51 msecs (HTTP/1.1 201) 2 headers in 76 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 10/10] 172.22.0.1 () {28 vars in 350 bytes} [Sun Jun 20 15:55:55 2021] GET /health => generated 43 bytes in 7 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 11/11] 172.22.0.1 () {32 vars in 402 bytes} [Sun Jun 20 15:55:55 2021] POST /setup => generated 31 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
...brutally killing workers...
worker 1 buried after 3 seconds
binary reloading uWSGI...
chdir() to /app
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (0.0.0.0:9090)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from /etc/uwsgi/uwsgi.ini
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jun 21 04:45:17 2021] ***
compiled with version: 8.3.0 on 20 June 2021 15:16:08
os: Linux-5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020
nodename: b7dad714e9df
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /app
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 0.0.0.0:9090 fd 3
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jun 21 04:47:40 2021] ***
compiled with version: 8.3.0 on 20 June 2021 15:16:08
os: Linux-5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020
nodename: c0c46da2de15
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /app
writing pidfile to /tmp/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.10 (default, May 12 2021, 16:05:48)  [GCC 8.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55848b2da7e0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 7 seconds on interpreter 0x55848b2da7e0 pid: 11 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 11)
spawned uWSGI worker 1 (pid: 21, cores: 1)
[pid: 21|app: 0|req: 1/1] 172.22.0.1 () {46 vars in 1425 bytes} [Mon Jun 21 04:47:47 2021] GET / => generated 43 bytes in 61 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 2/2] 172.22.0.1 () {32 vars in 403 bytes} [Mon Jun 21 04:49:21 2021] POST /train => generated 47 bytes in 33 msecs (HTTP/1.1 201) 2 headers in 76 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 3/3] 172.22.0.1 () {32 vars in 403 bytes} [Mon Jun 21 04:49:25 2021] POST /train => generated 47 bytes in 10 msecs (HTTP/1.1 201) 2 headers in 76 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 4/4] 172.22.0.1 () {46 vars in 1425 bytes} [Mon Jun 21 04:49:58 2021] GET / => generated 43 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 5/5] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 04:50:34 2021] GET /health => generated 43 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[2021-06-21 04:50:34,453] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 49, in _setup
    model = _manager.fetch(project, schema, force_reload, hostname=hostname, access_token=access_token)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 217, in fetch
    return cls.get_or_create(project, label_config, force_reload, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 204, in get_or_create
    cls.create(project, label_config, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 191, in create
    model=cls.model_class(label_config=label_config, train_output=train_output, **kwargs),
  File "./model_1_river.py", line 34, in __init__
    self.load_update_model = self.train_output['model_file']
KeyError: 'model_file'

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 49, in _setup
    model = _manager.fetch(project, schema, force_reload, hostname=hostname, access_token=access_token)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 217, in fetch
    return cls.get_or_create(project, label_config, force_reload, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 204, in get_or_create
    cls.create(project, label_config, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 191, in create
    model=cls.model_class(label_config=label_config, train_output=train_output, **kwargs),
  File "./model_1_river.py", line 34, in __init__
    self.load_update_model = self.train_output['model_file']
KeyError: 'model_file'

[pid: 21|app: 0|req: 6/6] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 04:50:34 2021] POST /setup => generated 1160 bytes in 15 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 7/7] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 04:51:15 2021] GET /health => generated 43 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[2021-06-21 04:51:15,594] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 49, in _setup
    model = _manager.fetch(project, schema, force_reload, hostname=hostname, access_token=access_token)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 217, in fetch
    return cls.get_or_create(project, label_config, force_reload, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 204, in get_or_create
    cls.create(project, label_config, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 191, in create
    model=cls.model_class(label_config=label_config, train_output=train_output, **kwargs),
  File "./model_1_river.py", line 34, in __init__
    self.load_update_model = self.train_output['model_file']
KeyError: 'model_file'

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 49, in _setup
    model = _manager.fetch(project, schema, force_reload, hostname=hostname, access_token=access_token)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 217, in fetch
    return cls.get_or_create(project, label_config, force_reload, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 204, in get_or_create
    cls.create(project, label_config, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 191, in create
    model=cls.model_class(label_config=label_config, train_output=train_output, **kwargs),
  File "./model_1_river.py", line 34, in __init__
    self.load_update_model = self.train_output['model_file']
KeyError: 'model_file'

[pid: 21|app: 0|req: 8/8] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 04:51:15 2021] POST /setup => generated 1160 bytes in 6 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 9/9] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 04:51:25 2021] GET /health => generated 43 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[2021-06-21 04:51:25,544] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 49, in _setup
    model = _manager.fetch(project, schema, force_reload, hostname=hostname, access_token=access_token)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 217, in fetch
    return cls.get_or_create(project, label_config, force_reload, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 204, in get_or_create
    cls.create(project, label_config, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 191, in create
    model=cls.model_class(label_config=label_config, train_output=train_output, **kwargs),
  File "./model_1_river.py", line 34, in __init__
    self.load_update_model = self.train_output['model_file']
KeyError: 'model_file'

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 49, in _setup
    model = _manager.fetch(project, schema, force_reload, hostname=hostname, access_token=access_token)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 217, in fetch
    return cls.get_or_create(project, label_config, force_reload, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 204, in get_or_create
    cls.create(project, label_config, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 191, in create
    model=cls.model_class(label_config=label_config, train_output=train_output, **kwargs),
  File "./model_1_river.py", line 34, in __init__
    self.load_update_model = self.train_output['model_file']
KeyError: 'model_file'

[pid: 21|app: 0|req: 10/10] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 04:51:25 2021] POST /setup => generated 1160 bytes in 7 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 11/11] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 04:51:35 2021] GET /health => generated 43 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[2021-06-21 04:51:35,194] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 49, in _setup
    model = _manager.fetch(project, schema, force_reload, hostname=hostname, access_token=access_token)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 217, in fetch
    return cls.get_or_create(project, label_config, force_reload, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 204, in get_or_create
    cls.create(project, label_config, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 191, in create
    model=cls.model_class(label_config=label_config, train_output=train_output, **kwargs),
  File "./model_1_river.py", line 34, in __init__
    self.load_update_model = self.train_output['model_file']
KeyError: 'model_file'

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 49, in _setup
    model = _manager.fetch(project, schema, force_reload, hostname=hostname, access_token=access_token)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 217, in fetch
    return cls.get_or_create(project, label_config, force_reload, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 204, in get_or_create
    cls.create(project, label_config, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 191, in create
    model=cls.model_class(label_config=label_config, train_output=train_output, **kwargs),
  File "./model_1_river.py", line 34, in __init__
    self.load_update_model = self.train_output['model_file']
KeyError: 'model_file'

[pid: 21|app: 0|req: 12/12] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 04:51:35 2021] POST /setup => generated 1160 bytes in 9 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 13/13] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 04:51:35 2021] GET /health => generated 43 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[2021-06-21 04:51:35,542] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 49, in _setup
    model = _manager.fetch(project, schema, force_reload, hostname=hostname, access_token=access_token)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 217, in fetch
    return cls.get_or_create(project, label_config, force_reload, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 204, in get_or_create
    cls.create(project, label_config, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 191, in create
    model=cls.model_class(label_config=label_config, train_output=train_output, **kwargs),
  File "./model_1_river.py", line 34, in __init__
    self.load_update_model = self.train_output['model_file']
KeyError: 'model_file'

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 49, in _setup
    model = _manager.fetch(project, schema, force_reload, hostname=hostname, access_token=access_token)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 217, in fetch
    return cls.get_or_create(project, label_config, force_reload, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 204, in get_or_create
    cls.create(project, label_config, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 191, in create
    model=cls.model_class(label_config=label_config, train_output=train_output, **kwargs),
  File "./model_1_river.py", line 34, in __init__
    self.load_update_model = self.train_output['model_file']
KeyError: 'model_file'

[pid: 21|app: 0|req: 14/14] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 04:51:35 2021] POST /setup => generated 1160 bytes in 5 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 15/15] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 04:51:35 2021] GET /health => generated 43 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[2021-06-21 04:51:35,983] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 49, in _setup
    model = _manager.fetch(project, schema, force_reload, hostname=hostname, access_token=access_token)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 217, in fetch
    return cls.get_or_create(project, label_config, force_reload, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 204, in get_or_create
    cls.create(project, label_config, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 191, in create
    model=cls.model_class(label_config=label_config, train_output=train_output, **kwargs),
  File "./model_1_river.py", line 34, in __init__
    self.load_update_model = self.train_output['model_file']
KeyError: 'model_file'

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 49, in _setup
    model = _manager.fetch(project, schema, force_reload, hostname=hostname, access_token=access_token)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 217, in fetch
    return cls.get_or_create(project, label_config, force_reload, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 204, in get_or_create
    cls.create(project, label_config, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 191, in create
    model=cls.model_class(label_config=label_config, train_output=train_output, **kwargs),
  File "./model_1_river.py", line 34, in __init__
    self.load_update_model = self.train_output['model_file']
KeyError: 'model_file'

[pid: 21|app: 0|req: 16/16] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 04:51:35 2021] POST /setup => generated 1160 bytes in 5 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 17/17] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 04:51:36 2021] GET /health => generated 43 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[2021-06-21 04:51:36,248] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 49, in _setup
    model = _manager.fetch(project, schema, force_reload, hostname=hostname, access_token=access_token)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 217, in fetch
    return cls.get_or_create(project, label_config, force_reload, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 204, in get_or_create
    cls.create(project, label_config, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 191, in create
    model=cls.model_class(label_config=label_config, train_output=train_output, **kwargs),
  File "./model_1_river.py", line 34, in __init__
    self.load_update_model = self.train_output['model_file']
KeyError: 'model_file'

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 49, in _setup
    model = _manager.fetch(project, schema, force_reload, hostname=hostname, access_token=access_token)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 217, in fetch
    return cls.get_or_create(project, label_config, force_reload, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 204, in get_or_create
    cls.create(project, label_config, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 191, in create
    model=cls.model_class(label_config=label_config, train_output=train_output, **kwargs),
  File "./model_1_river.py", line 34, in __init__
    self.load_update_model = self.train_output['model_file']
KeyError: 'model_file'

[pid: 21|app: 0|req: 18/18] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 04:51:36 2021] POST /setup => generated 1160 bytes in 7 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 19/19] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 04:51:36 2021] GET /health => generated 43 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[2021-06-21 04:51:36,508] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 49, in _setup
    model = _manager.fetch(project, schema, force_reload, hostname=hostname, access_token=access_token)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 217, in fetch
    return cls.get_or_create(project, label_config, force_reload, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 204, in get_or_create
    cls.create(project, label_config, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 191, in create
    model=cls.model_class(label_config=label_config, train_output=train_output, **kwargs),
  File "./model_1_river.py", line 34, in __init__
    self.load_update_model = self.train_output['model_file']
KeyError: 'model_file'

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 49, in _setup
    model = _manager.fetch(project, schema, force_reload, hostname=hostname, access_token=access_token)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 217, in fetch
    return cls.get_or_create(project, label_config, force_reload, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 204, in get_or_create
    cls.create(project, label_config, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 191, in create
    model=cls.model_class(label_config=label_config, train_output=train_output, **kwargs),
  File "./model_1_river.py", line 34, in __init__
    self.load_update_model = self.train_output['model_file']
KeyError: 'model_file'

[pid: 21|app: 0|req: 20/20] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 04:51:36 2021] POST /setup => generated 1160 bytes in 7 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jun 21 04:57:23 2021] ***
compiled with version: 8.3.0 on 20 June 2021 15:16:08
os: Linux-5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020
nodename: fd011d5a310a
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /app
writing pidfile to /tmp/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.10 (default, May 12 2021, 16:05:48)  [GCC 8.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x5610307db7e0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 10 seconds on interpreter 0x5610307db7e0 pid: 10 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 10)
spawned uWSGI worker 1 (pid: 20, cores: 1)
[pid: 20|app: 0|req: 1/1] 172.22.0.1 () {46 vars in 1425 bytes} [Mon Jun 21 04:57:33 2021] GET / => generated 43 bytes in 7 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 2/2] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 04:57:37 2021] GET /health => generated 43 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[2021-06-21 04:57:37,285] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 49, in _setup
    model = _manager.fetch(project, schema, force_reload, hostname=hostname, access_token=access_token)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 217, in fetch
    return cls.get_or_create(project, label_config, force_reload, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 204, in get_or_create
    cls.create(project, label_config, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 191, in create
    model=cls.model_class(label_config=label_config, train_output=train_output, **kwargs),
  File "./model_1_river.py", line 34, in __init__
    self.load_update_model = joblib.load("model_trained_human.bin")
  File "/usr/local/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 577, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'model_trained_human.bin'

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 49, in _setup
    model = _manager.fetch(project, schema, force_reload, hostname=hostname, access_token=access_token)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 217, in fetch
    return cls.get_or_create(project, label_config, force_reload, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 204, in get_or_create
    cls.create(project, label_config, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 191, in create
    model=cls.model_class(label_config=label_config, train_output=train_output, **kwargs),
  File "./model_1_river.py", line 34, in __init__
    self.load_update_model = joblib.load("model_trained_human.bin")
  File "/usr/local/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 577, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'model_trained_human.bin'

[pid: 20|app: 0|req: 3/3] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 04:57:37 2021] POST /setup => generated 1417 bytes in 33 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
...brutally killing workers...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /app
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (0.0.0.0:9090)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from /etc/uwsgi/uwsgi.ini
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jun 21 05:01:39 2021] ***
compiled with version: 8.3.0 on 20 June 2021 15:16:08
os: Linux-5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020
nodename: fd011d5a310a
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /app
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 0.0.0.0:9090 fd 3
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jun 21 05:02:33 2021] ***
compiled with version: 8.3.0 on 20 June 2021 15:16:08
os: Linux-5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020
nodename: 4d17d66cf212
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /app
writing pidfile to /tmp/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.10 (default, May 12 2021, 16:05:48)  [GCC 8.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55f73c84b7e0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 7 seconds on interpreter 0x55f73c84b7e0 pid: 11 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 11)
spawned uWSGI worker 1 (pid: 21, cores: 1)
[pid: 21|app: 0|req: 1/1] 172.22.0.1 () {46 vars in 1425 bytes} [Mon Jun 21 05:02:40 2021] GET / => generated 43 bytes in 8 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 2/2] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 05:02:43 2021] GET /health => generated 43 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[2021-06-21 05:02:43,726] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 49, in _setup
    model = _manager.fetch(project, schema, force_reload, hostname=hostname, access_token=access_token)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 217, in fetch
    return cls.get_or_create(project, label_config, force_reload, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 204, in get_or_create
    cls.create(project, label_config, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 191, in create
    model=cls.model_class(label_config=label_config, train_output=train_output, **kwargs),
  File "./model_1_river.py", line 34, in __init__
    self.model_file = self.train_output['model_file']
KeyError: 'model_file'

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 49, in _setup
    model = _manager.fetch(project, schema, force_reload, hostname=hostname, access_token=access_token)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 217, in fetch
    return cls.get_or_create(project, label_config, force_reload, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 204, in get_or_create
    cls.create(project, label_config, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 191, in create
    model=cls.model_class(label_config=label_config, train_output=train_output, **kwargs),
  File "./model_1_river.py", line 34, in __init__
    self.model_file = self.train_output['model_file']
KeyError: 'model_file'

[pid: 21|app: 0|req: 3/3] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 05:02:43 2021] POST /setup => generated 1153 bytes in 21 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 4/4] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 05:03:49 2021] GET /health => generated 43 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[2021-06-21 05:03:49,151] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 49, in _setup
    model = _manager.fetch(project, schema, force_reload, hostname=hostname, access_token=access_token)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 217, in fetch
    return cls.get_or_create(project, label_config, force_reload, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 204, in get_or_create
    cls.create(project, label_config, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 191, in create
    model=cls.model_class(label_config=label_config, train_output=train_output, **kwargs),
  File "./model_1_river.py", line 34, in __init__
    self.model_file = self.train_output['model_file']
KeyError: 'model_file'

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 49, in _setup
    model = _manager.fetch(project, schema, force_reload, hostname=hostname, access_token=access_token)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 217, in fetch
    return cls.get_or_create(project, label_config, force_reload, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 204, in get_or_create
    cls.create(project, label_config, train_output, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 191, in create
    model=cls.model_class(label_config=label_config, train_output=train_output, **kwargs),
  File "./model_1_river.py", line 34, in __init__
    self.model_file = self.train_output['model_file']
KeyError: 'model_file'

[pid: 21|app: 0|req: 5/5] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 05:03:49 2021] POST /setup => generated 1153 bytes in 16 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
...brutally killing workers...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /app
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (0.0.0.0:9090)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from /etc/uwsgi/uwsgi.ini
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jun 21 05:09:53 2021] ***
compiled with version: 8.3.0 on 20 June 2021 15:16:08
os: Linux-5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020
nodename: 4d17d66cf212
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /app
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 0.0.0.0:9090 fd 3
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jun 21 05:10:44 2021] ***
compiled with version: 8.3.0 on 20 June 2021 15:16:08
os: Linux-5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020
nodename: 494bb4bcbb39
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /app
writing pidfile to /tmp/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.10 (default, May 12 2021, 16:05:48)  [GCC 8.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x559ddde017e0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 8 seconds on interpreter 0x559ddde017e0 pid: 10 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 10)
spawned uWSGI worker 1 (pid: 20, cores: 1)
[pid: 20|app: 0|req: 1/1] 172.22.0.1 () {46 vars in 1425 bytes} [Mon Jun 21 05:10:52 2021] GET / => generated 43 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 2/2] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 05:10:58 2021] GET /health => generated 43 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 3/3] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 05:10:58 2021] POST /setup => generated 31 bytes in 11 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 4/4] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 05:11:50 2021] GET /health => generated 43 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 5/5] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 05:11:50 2021] POST /setup => generated 31 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[2021-06-21 05:11:50,672] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 31, in _predict
    predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 277, in predict
    predictions = m.model.predict(tasks, **kwargs)
  File "./model_1_river.py", line 62, in predict
    predicted_label = self.load_update_model.predict_one(input_text)
AttributeError: 'StockDataClassifier' object has no attribute 'load_update_model'

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 31, in _predict
    predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 277, in predict
    predictions = m.model.predict(tasks, **kwargs)
  File "./model_1_river.py", line 62, in predict
    predicted_label = self.load_update_model.predict_one(input_text)
AttributeError: 'StockDataClassifier' object has no attribute 'load_update_model'

[pid: 20|app: 0|req: 6/6] 172.22.0.1 () {32 vars in 408 bytes} [Mon Jun 21 05:11:50 2021] POST /predict => generated 879 bytes in 7 msecs (HTTP/1.1 500) 2 headers in 91 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 7/7] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 05:11:53 2021] GET /health => generated 43 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 8/8] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 05:11:53 2021] POST /setup => generated 31 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[2021-06-21 05:11:53,594] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 31, in _predict
    predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 277, in predict
    predictions = m.model.predict(tasks, **kwargs)
  File "./model_1_river.py", line 62, in predict
    predicted_label = self.load_update_model.predict_one(input_text)
AttributeError: 'StockDataClassifier' object has no attribute 'load_update_model'

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 31, in _predict
    predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 277, in predict
    predictions = m.model.predict(tasks, **kwargs)
  File "./model_1_river.py", line 62, in predict
    predicted_label = self.load_update_model.predict_one(input_text)
AttributeError: 'StockDataClassifier' object has no attribute 'load_update_model'

[pid: 20|app: 0|req: 9/9] 172.22.0.1 () {32 vars in 408 bytes} [Mon Jun 21 05:11:53 2021] POST /predict => generated 879 bytes in 11 msecs (HTTP/1.1 500) 2 headers in 91 bytes (1 switches on core 0)
...brutally killing workers...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /app
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (0.0.0.0:9090)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from /etc/uwsgi/uwsgi.ini
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jun 21 05:14:32 2021] ***
compiled with version: 8.3.0 on 20 June 2021 15:16:08
os: Linux-5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020
nodename: 494bb4bcbb39
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /app
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 0.0.0.0:9090 fd 3
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jun 21 05:15:21 2021] ***
compiled with version: 8.3.0 on 20 June 2021 15:16:08
os: Linux-5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020
nodename: c6958188214c
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /app
writing pidfile to /tmp/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.10 (default, May 12 2021, 16:05:48)  [GCC 8.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55a1ec7c07e0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 6 seconds on interpreter 0x55a1ec7c07e0 pid: 11 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 11)
spawned uWSGI worker 1 (pid: 21, cores: 1)
[pid: 21|app: 0|req: 1/1] 172.22.0.1 () {46 vars in 1425 bytes} [Mon Jun 21 05:16:01 2021] GET / => generated 43 bytes in 7 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 2/2] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 05:16:06 2021] GET /health => generated 43 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 3/3] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 05:16:06 2021] POST /setup => generated 31 bytes in 967 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 4/4] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 05:16:47 2021] GET /health => generated 43 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 5/5] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 05:16:47 2021] POST /setup => generated 31 bytes in 4 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
{'Positive': 0.10650798618894915, 'Negative': 0.893492013811053} --> 89.35
{'Positive': 0.985456921919573, 'Negative': 0.014543078080429268} --> 98.55
{'Positive': 0.9996803959482776, 'Negative': 0.00031960405172184157} --> 99.97
{'Positive': 0.9999976236940381, 'Negative': 2.3763059612203056e-06} --> 100.0
{'Positive': 0.25727419305620236, 'Negative': 0.7427258069437851} --> 74.27
{'Positive': 8.834022539940388e-05, 'Negative': 0.9999116597745946} --> 99.99
{'Positive': 0.9815849991487772, 'Negative': 0.018415000851223957} --> 98.16
{'Positive': 0.9744950030272269, 'Negative': 0.025504996972774543} --> 97.45
{'Positive': 0.9623413381722057, 'Negative': 0.03765866182779326} --> 96.23
{'Positive': 0.4685417719028487, 'Negative': 0.531458228097146} --> 53.15
{'Positive': 0.8748629323511259, 'Negative': 0.12513706764887764} --> 87.49
{'Positive': 0.9998697433554443, 'Negative': 0.00013025664455291702} --> 99.99
{'Positive': 0.3046390669492096, 'Negative': 0.6953609330507942} --> 69.54
{'Positive': 0.0050697428971540085, 'Negative': 0.9949302571028539} --> 99.49
{'Positive': 0.9966941442920894, 'Negative': 0.003305855707910612} --> 99.67
{'Positive': 0.34714588044643785, 'Negative': 0.6528541195535613} --> 65.29
{'Positive': 0.7347041465730899, 'Negative': 0.2652958534269167} --> 73.47
{'Positive': 0.9665575657965864, 'Negative': 0.03344243420342517} --> 96.66
{'Positive': 0.8688859087023737, 'Negative': 0.13111409129762433} --> 86.89
{'Positive': 0.09640139045390722, 'Negative': 0.903598609546096} --> 90.36
{'Positive': 0.5194690135849582, 'Negative': 0.48053098641504166} --> 51.95
{'Positive': 0.0015985286179199057, 'Negative': 0.9984014713820787} --> 99.84
{'Positive': 0.9978285774777202, 'Negative': 0.002171422522286761} --> 99.78
{'Positive': 0.5724728221601276, 'Negative': 0.42752717783987115} --> 57.25
{'Positive': 0.797317862774286, 'Negative': 0.20268213722571815} --> 79.73
{'Positive': 0.8624206731671104, 'Negative': 0.13757932683289167} --> 86.24
{'Positive': 0.4736848924042398, 'Negative': 0.5263151075957665} --> 52.63
{'Positive': 0.992981673027608, 'Negative': 0.007018326972389144} --> 99.3
{'Positive': 0.6672825869976167, 'Negative': 0.3327174130023856} --> 66.73
{'Positive': 0.969489471746183, 'Negative': 0.03051052825381403} --> 96.95
[pid: 21|app: 0|req: 6/6] 172.22.0.1 () {32 vars in 408 bytes} [Mon Jun 21 05:16:48 2021] POST /predict => generated 3642 bytes in 233 msecs (HTTP/1.1 200) 2 headers in 73 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 7/7] 172.22.0.1 () {32 vars in 403 bytes} [Mon Jun 21 05:17:15 2021] POST /train => generated 47 bytes in 10 msecs (HTTP/1.1 201) 2 headers in 76 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 8/8] 172.22.0.1 () {32 vars in 403 bytes} [Mon Jun 21 05:17:20 2021] POST /train => generated 47 bytes in 10 msecs (HTTP/1.1 201) 2 headers in 76 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 9/9] 172.22.0.1 () {32 vars in 403 bytes} [Mon Jun 21 05:18:39 2021] POST /train => generated 47 bytes in 9 msecs (HTTP/1.1 201) 2 headers in 76 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 10/10] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 05:18:40 2021] GET /health => generated 43 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 11/11] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 05:18:40 2021] POST /setup => generated 31 bytes in 1425 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 12/12] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 05:19:49 2021] GET /health => generated 43 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 13/13] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 05:19:49 2021] POST /setup => generated 31 bytes in 1221 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 14/14] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 05:19:51 2021] GET /health => generated 43 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 15/15] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 05:19:51 2021] POST /setup => generated 31 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 16/16] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 05:19:51 2021] GET /health => generated 43 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 17/17] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 05:19:51 2021] POST /setup => generated 31 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 18/18] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 05:19:51 2021] GET /health => generated 43 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 19/19] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 05:19:51 2021] POST /setup => generated 31 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 20/20] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 05:19:52 2021] GET /health => generated 43 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 21/21] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 05:19:52 2021] POST /setup => generated 31 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 22/22] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 05:19:53 2021] GET /health => generated 43 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 23/23] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 05:19:53 2021] POST /setup => generated 31 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 24/24] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 05:19:54 2021] GET /health => generated 43 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 25/25] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 05:19:54 2021] POST /setup => generated 31 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 26/26] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 05:19:54 2021] GET /health => generated 43 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 27/27] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 05:19:54 2021] POST /setup => generated 31 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 28/28] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 05:21:17 2021] GET /health => generated 43 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 29/29] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 05:21:17 2021] POST /setup => generated 31 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
{'Positive': 0.504477669118935, 'Negative': 0.495522330881067} --> 50.45
[pid: 21|app: 0|req: 30/30] 172.22.0.1 () {32 vars in 407 bytes} [Mon Jun 21 05:21:17 2021] POST /predict => generated 163 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 31/31] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 05:21:17 2021] GET /health => generated 43 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 21|app: 0|req: 32/32] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 05:21:17 2021] POST /setup => generated 31 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
{'Positive': 0.504477669118935, 'Negative': 0.495522330881067} --> 50.45
[pid: 21|app: 0|req: 33/33] 172.22.0.1 () {32 vars in 407 bytes} [Mon Jun 21 05:21:17 2021] POST /predict => generated 163 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
...brutally killing workers...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /app
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (0.0.0.0:9090)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from /etc/uwsgi/uwsgi.ini
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jun 21 05:24:55 2021] ***
compiled with version: 8.3.0 on 20 June 2021 15:16:08
os: Linux-5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020
nodename: c6958188214c
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /app
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 0.0.0.0:9090 fd 3
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jun 21 05:25:46 2021] ***
compiled with version: 8.3.0 on 20 June 2021 15:16:08
os: Linux-5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020
nodename: bd0f5f2d6a0e
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /app
writing pidfile to /tmp/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.10 (default, May 12 2021, 16:05:48)  [GCC 8.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55a69d9f87e0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 5 seconds on interpreter 0x55a69d9f87e0 pid: 10 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 10)
spawned uWSGI worker 1 (pid: 20, cores: 1)
[pid: 20|app: 0|req: 1/1] 172.22.0.1 () {46 vars in 1425 bytes} [Mon Jun 21 05:26:33 2021] GET / => generated 43 bytes in 7 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 2/2] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 05:26:37 2021] GET /health => generated 43 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 3/3] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 05:26:37 2021] POST /setup => generated 31 bytes in 890 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 4/4] 172.22.0.1 () {32 vars in 403 bytes} [Mon Jun 21 05:26:57 2021] POST /train => generated 47 bytes in 12 msecs (HTTP/1.1 201) 2 headers in 76 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 5/5] 172.22.0.1 () {32 vars in 403 bytes} [Mon Jun 21 05:27:02 2021] POST /train => generated 47 bytes in 8 msecs (HTTP/1.1 201) 2 headers in 76 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 6/6] 172.22.0.1 () {32 vars in 403 bytes} [Mon Jun 21 05:27:31 2021] POST /train => generated 47 bytes in 14 msecs (HTTP/1.1 201) 2 headers in 76 bytes (2 switches on core 0)
[pid: 20|app: 0|req: 7/7] 172.22.0.1 () {32 vars in 403 bytes} [Mon Jun 21 05:27:39 2021] POST /train => generated 47 bytes in 11 msecs (HTTP/1.1 201) 2 headers in 76 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 8/8] 172.22.0.1 () {32 vars in 403 bytes} [Mon Jun 21 05:28:02 2021] POST /train => generated 47 bytes in 10 msecs (HTTP/1.1 201) 2 headers in 76 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 9/9] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 05:28:03 2021] GET /health => generated 43 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 10/10] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 05:28:03 2021] POST /setup => generated 31 bytes in 821 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 11/11] 172.22.0.1 () {32 vars in 403 bytes} [Mon Jun 21 05:37:37 2021] POST /train => generated 47 bytes in 461 msecs (HTTP/1.1 201) 2 headers in 76 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 12/12] 172.22.0.1 () {32 vars in 403 bytes} [Mon Jun 21 05:37:45 2021] POST /train => generated 47 bytes in 22 msecs (HTTP/1.1 201) 2 headers in 76 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 13/13] 172.22.0.1 () {32 vars in 403 bytes} [Mon Jun 21 05:38:01 2021] POST /train => generated 47 bytes in 19 msecs (HTTP/1.1 201) 2 headers in 76 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 14/14] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 05:38:02 2021] GET /health => generated 43 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 15/15] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 05:38:02 2021] POST /setup => generated 31 bytes in 1493 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 16/16] 172.22.0.1 () {28 vars in 350 bytes} [Mon Jun 21 05:54:14 2021] GET /health => generated 43 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 17/17] 172.22.0.1 () {32 vars in 402 bytes} [Mon Jun 21 05:54:14 2021] POST /setup => generated 31 bytes in 4893 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
{'Positive': 0.9999710875790722, 'Negative': 2.89124209289699e-05} --> 100.0
{'Positive': 0.7261473464112396, 'Negative': 0.273852653588762} --> 72.61
[pid: 20|app: 0|req: 18/18] 172.22.0.1 () {32 vars in 407 bytes} [Mon Jun 21 05:54:19 2021] POST /predict => generated 283 bytes in 15 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
[pid: 20|app: 0|req: 19/19] 172.22.0.1 () {32 vars in 403 bytes} [Mon Jun 21 05:58:12 2021] POST /train => generated 47 bytes in 21 msecs (HTTP/1.1 201) 2 headers in 76 bytes (2 switches on core 0)
